name: CI-CD pipeline
env:
  TFSTATE_S3_BUCKET_NAME : "cluster-state"
  AWS_REGION_NAME        : "us-west-1"

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
      - uses: actions/checkout@v2

      - name: Run a runner init script
        run: |
          export work_dir=`pwd`
          chmod +x scripts/*.sh
          ./scripts/runner-init.sh && cd $work_dir
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    :  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region           :  ${{ env.AWS_REGION_NAME }}      
          
      - name: Run-tfinit-command
        run: terraform init
      
      - name: Run-tfplan-command
        if: steps.Run-tfinit-command.outputs.exit_code == 0      
        run: terraform plan -out tfplan
        
      - name: Run-tfapply-command
        if: steps.Run-tfplan-command.outputs.exit_code == 0
        run: terraform apply -auto-approve "tfplan"
